<a href="https://colab.research.google.com/github/Rakesh889/Rakesh/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
# 0 dimensional Array
b=np.array(54)
print(b)
print(b.ndim)

54
0


In [ ]:
# 1 dimensional Array
a=np.array([1,2,3])
print(a)
type(a)
print(a.ndim)

[1 2 3]
1


In [ ]:
# 2 dimensional Array
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [ ]:
# 3 dimensional Array
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)
print(d.ndim)
print(type(d))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
<class 'numpy.ndarray'>
